server:
  port: 7965

spring:
  application:
    name: xue-api
  redis:
    host: localhost
    port: 6379

logging:
  level:
    root: info
    org.mybatis: debug
    com.xueershangda: debug
    com.vteba: info
  path: ~/
  file: xue-api.log